CREATE TABLE IF NOT EXISTS album_content_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    template_code VARCHAR(64) NOT NULL COMMENT '模板代码, 对外稳定标识',
    name VARCHAR(128) NOT NULL COMMENT '模板名称',
    description VARCHAR(512) NULL COMMENT '模板说明',
    book_type VARCHAR(32) NULL COMMENT '适用书册类型, NULL=通用',
    page_type VARCHAR(32) NOT NULL COMMENT '页面类型: cover/title/preface/content 等',
    category VARCHAR(32) NULL COMMENT '模板分类: minimal/magazine/story 等',
    theme_code VARCHAR(64) NULL COMMENT '前端主题或模板族代码',
    schema_version VARCHAR(16) NOT NULL DEFAULT '2.0' COMMENT 'jsonSource schemaVersion',
    json_source LONGTEXT NOT NULL COMMENT '模板初始 JSON 数据源',
    preview_file_id BIGINT NULL COMMENT '-> storage_file_object.id, 模板预览图',
    created_by_user_id BIGINT NULL COMMENT '-> identity_user.id, 创建人',
    is_built_in TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否内置模板',
    is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值, 越小越靠前',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_album_content_template_code (template_code),
    INDEX idx_album_content_template_lookup (is_active, book_type, page_type, sort_order, id),
    INDEX idx_album_content_template_user (created_by_user_id, updated_at),
    CONSTRAINT fk_album_content_template_preview_file FOREIGN KEY (preview_file_id) REFERENCES storage_file_object (id),
    CONSTRAINT fk_album_content_template_user FOREIGN KEY (created_by_user_id) REFERENCES identity_user (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='相册内容模板, 提供可编辑的初始 jsonSource';