-- Placeholder for the first AlbumTemplates list stored procedure.
-- Keep the result shape aligned with AlbumTemplateListItemResponse.
-- Suggested parameters:
--   IN p_keyword VARCHAR(128)
--   IN p_page_number INT
--   IN p_page_size INT

-- CREATE PROCEDURE usp_AlbumTemplates_List(...)
-- BEGIN
--     -- TODO: implement list query for album templates.
-- END;